name: Auto assign

on:
  - pull_request

jobs:
  auto-assign:
    name: auto assign
    runs-on: ubuntu-latest
    env:
      ASSIGNEES: |-
        sasaplus1
        sasaplus1
        sasaplus1
      PEOPLE: 1
    steps:
      - id: assignees
        run: |
          echo -n "$ASSIGNEES" | sort -R | head -n "$PEOPLE" | xargs printf -- '"%s",' | tee assignees.txt
          echo "::set-output name=assignees::$(cat assignees.txt)"
      - uses: actions/github-script@0.3.0
        if: startsWith(github.head_ref, 'auto-assign/')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addAssignees({
              ...context.issue,
              issue_number: context.issue.number,
              assignees: [${{ steps.assignees.assignees }}],
            });
