name: Auto assign

on:
  - pull_request

jobs:
  auto-assign:
    name: auto assign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install -g lodash
      - uses: actions/github-script@0.3.0
        if: startsWith(github.head_ref, 'auto-assign/')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // const _ = require('lodash');
            // const assignees = _.sampleSize([
            //   'sasaplus1',
            // ], 1);
            github.issues.addAssignees({
              ...context.issue,
              assignees: ['sasaplus1']
            });
