name: Auto assign

on:
  pull_request:
    branches:
      - master

jobs:
  auto-assign:
    name: auto assign
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
