name: Auto assign

on:
  - pull_request

jobs:
  auto-assign:
    name: auto assign
    if: startsWith(github.head_ref, 'auto-assign/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
