name: Auto assign

on:
  - pull_request

jobs:
  auto-assign:
    name: auto assign
    runs-on: ubuntu-latest
    env:
      MEMBERS: |-
        sasaplus1
      PEOPLES: 1
    steps:
      - id: pick
        run: |
          echo -n "$MEMBERS" | sort -R | head -n "$PEOPLES" | xargs printf -- '"%s",' > assignees.txt
          echo "::set-output name=assignees::$(cat assignees.txt)"
      - uses: actions/github-script@0.3.0
        if: startsWith(github.head_ref, 'auto-assign/')
        env:
          ASSIGNEES: ${{ steps.pick.outputs.assignees }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addAssignees({
              ...context.issue,
              assignees: [process.env.ASSIGNEES.split(',')],
            });
