name: merged

on:
  pull_request:
    branches:
      - '*'
    types:
      - closed

jobs:
  merged:
    name: merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo "${GITHUB_BASE_REF}" "${GITHUB_HEAD_REF}"
      - run: git branch -a
      - run: git tag
      - run: git log --all --graph --date=short
      - run: git show "${GITHUB_BASE_REF}" 
      - run: git show "${GITHUB_HEAD_REF}" 
