name: merged

on:
  pull_request:
    branches:
      - '*'
    types:
      - closed

jobs:
  merged:
    name: merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_BASE_REF}" "${GITHUB_HEAD_REF}"
