name: push-tag

on:
  push:
    branches:
      - master

jobs:
  push-tag:
    name: push tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          debug: true
          github-token: ${{ secrets.PAT }}
          script: |
            github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: 'tag-1-' + (Math.random() * 10000 >> 0),
              message: '',
              object: context.sha,
              type: 'commit'
            });
