name: repository name

on:
  - push
  - pull_request_target
  - workflow_dispatch

jobs:
  repository-name:
    name: repository name
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_REPOSITORY}"
      - run: echo "${GITHUB_REPOSITORY_OWNER}"
      - run: echo "${GITHUB_REF}"
      - run: echo "${GITHUB_BASE_REF}"
      - run: echo "${GITHUB_HEAD_REF}"
      - run: echo "${GITHUB_EVENT_NAME}"
      - run: echo "${GITHUB_EVENT_PATH}"
      - run: echo "${GITHUB_EVENT}"
      - run: echo "${DATA1}" "${DATA2}"
        env:
          DATA1: ${{ github.event.push.ref }}
          DATA2: ${{ github.event.push.repository.full_name }}
      - run: echo "${DATA1}" "${DATA2}"
        env:
          DATA1: ${{ github.event.pull_request.base.repo.full_name }}
          DATA2: ${{ github.event.pull_request.head.repo.full_name }}
