name: repository name

on:
  - push
  - pull_request_target

jobs:
  repository-name:
    name: repository name
    runs-on: ubuntu-latest
    steps:
      - run: echo "${GITHUB_REPOSITORY}"
      - run: echo "${GITHUB_REF}"
      - run: echo "${GITHUB_BASE_REF}"
      - run: echo "${GITHUB_HEAD_REF}"
      - run: echo "${GITHUB_EVENT_NAME}"
      - run: echo "${GITHUB_EVENT_PATH}"
