name: sandbox

on:
  - push
  - pull_request

jobs:
  sandbox:
    name: sandbox
    strategy:
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - run: pwd
      - run: ls -la
        shell: bash
      - run: ls -la /
        shell: bash
      - id: set_data1
        run: echo "::set-output name=expr::$(expr 1 + 1)"
      - id: set_data2
        run: echo "::set-output name=path::${PATH}"
      - id: set_data3
        run: echo "::set-output name=cdir::$(pwd)"
      - run: |
          echo $EXPR
          echo $PATH
          echo $CDIR
        env:
          EXPR: ${{ steps.set_data1.outputs.expr }}
          PATH: ${{ steps.set_data2.outputs.path }}
          CDIR: ${{ steps.set_data3.outputs.cdir }}
      - run: echo $PATH | tr ':' '\n'
      - run: echo "/path/to/dir1" >> "$GITHUB_PATH"
      - run: echo "/path/to/dir2" >> "$GITHUB_PATH"
      - run: echo '/path/to/dir3' >> "$GITHUB_PATH"
      - run: echo $PATH | tr ':' '\n'
      - run: |
          echo "/path/to/dir4" >> "$GITHUB_PATH"
          echo "/path/to/dir5" >> "$GITHUB_PATH"
          echo '/path/to/dir6' >> "$GITHUB_PATH"
      - run: echo $PATH | tr ':' '\n'
      - id: boolean_check1
        run: echo '::set-output name=flag::true'
      - run: echo true
        if: steps.boolean_check1.outputs.flag
      - run: echo true
        if: steps.boolean_check1.outputs.flag == true
      - run: echo true
        if: steps.boolean_check1.outputs.flag == 'true'
      - id: boolean_check2
        run: echo '::set-output name=flag::1'
      - run: echo true
        if: steps.boolean_check2.outputs.flag
      - run: echo true
        if: steps.boolean_check2.outputs.flag == true
      - run: echo true
        if: steps.boolean_check2.outputs.flag == 'true'
      - id: boolean_check3
        run: echo '::set-output name=flag::'
      - run: echo false 
        if: steps.boolean_check3.outputs.flag
      - run: echo false
        if: steps.boolean_check3.outputs.flag == false
      - run: echo false
        if: steps.boolean_check3.outputs.flag == 'false'
      - id: boolean_check4
        run: echo '::set-output name=flag::${{ toJSON(true) }}'
      - run: echo false 
        if: steps.boolean_check4.outputs.flag
      - run: echo false
        if: steps.boolean_check4.outputs.flag == false
      - run: echo false
        if: steps.boolean_check4.outputs.flag == 'false'
      - run: echo $HOUSE
        env:
          HOUSE: ${{ env.HOME }}
      - run: type -tP google-chrome
        continue-on-error: true
      - run: |
          if [ 1 = 1 ]
          then
            echo 1
          else
            echo 2
          fi
        shell: bash
      - run: |
          set -x
          if [ 1 = 1 ]
          then
            echo 1
          else
            echo 2
          fi
        shell: bash
      - uses: actions/github-script@v5
        with:
          script: |
            github.request('POST /repos/${{ github.repository }}/git/refs', {
              ref: `refs/tags/${ Math.random().toString().slice(2) }`,
              sha: '${{ github.sha }}'
            });
