name: sandbox

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  sandbox:
    name: sandbox
    strategy:
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - run: pwd
      - run: ls -la
        shell: bash
      - run: ls -la /
        shell: bash
      - id: set_data1
        run: echo "::set-output name=expr::$(expr 1 + 1)"
      - id: set_data2
        run: echo "::set-output name=path::${PATH}"
      - id: set_data3
        run: echo "::set-output name=cdir::$(pwd)"
      - run: |
          echo $EXPR
          echo $PATH
          echo $CDIR
        env:
          EXPR: ${{ steps.set_data1.outputs.expr }}
          PATH: ${{ steps.set_data2.outputs.path }}
          CDIR: ${{ steps.set_data3.outputs.cdir }}
      - run: echo $PATH | tr ':' '\n'
      - run: echo "/path/to/dir1" >> "$GITHUB_PATH"
      - run: echo "/path/to/dir2" >> "$GITHUB_PATH"
      - run: echo '/path/to/dir3' >> "$GITHUB_PATH"
      - run: echo $PATH | tr ':' '\n'
      - run: |
          echo "/path/to/dir4" >> "$GITHUB_PATH"
          echo "/path/to/dir5" >> "$GITHUB_PATH"
          echo '/path/to/dir6' >> "$GITHUB_PATH"
      - run: echo $PATH | tr ':' '\n'
      - id: boolean_check1
        run: echo '::set-output name=flag::true'
      - run: echo true
        if: steps.boolean_check1.outputs.flag
      - run: echo true
        if: steps.boolean_check1.outputs.flag == true
      - run: echo true
        if: steps.boolean_check1.outputs.flag == 'true'
      - id: boolean_check2
        run: echo '::set-output name=flag::1'
      - run: echo true
        if: steps.boolean_check2.outputs.flag
      - run: echo true
        if: steps.boolean_check2.outputs.flag == true
      - run: echo true
        if: steps.boolean_check2.outputs.flag == 'true'
      - id: boolean_check3
        run: echo '::set-output name=flag::'
      - run: echo false 
        if: steps.boolean_check3.outputs.flag
      - run: echo false
        if: steps.boolean_check3.outputs.flag == false
      - run: echo false
        if: steps.boolean_check3.outputs.flag == 'false'
      - id: boolean_check4
        run: echo '::set-output name=flag::${{ toJSON(true) }}'
      - run: echo false 
        if: steps.boolean_check4.outputs.flag
      - run: echo false
        if: steps.boolean_check4.outputs.flag == false
      - run: echo false
        if: steps.boolean_check4.outputs.flag == 'false'
      - run: echo $HOUSE
        env:
          HOUSE: ${{ env.HOME }}
      - run: type -tP google-chrome
        continue-on-error: true
      - run: |
          if [ 1 = 1 ]
          then
            echo 1
          else
            echo 2
          fi
        shell: bash
      - run: |
          set -x
          if [ 1 = 1 ]
          then
            echo 1
          else
            echo 2
          fi
        shell: bash
    # - uses: actions/github-script@v5
    #   with:
    #     github-token: ${{ secrets.PAT }}
    #     script: |
    #       github.request('POST /repos/${{ github.repository }}/git/refs', {
    #         ref: `refs/tags/${ Math.random().toString().slice(2) }`,
    #         sha: '${{ github.sha }}'
    #       });
      - run: echo '[${{ github.server_url }}]' "[${GITHUB_SERVER_URL}]"
      - run: |
          set -x
          echo "HOGEHOGE=12321" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo $HOGEHOGE
          echo $GITHUB_ENV
      - run: |
          set -x
          echo $HOGEHOGE
          source $GITHUB_ENV
          echo $HOGEHOGE
          echo $GITHUB_ENV
      - run: echo "${{ github.ref_name }}"
      - run: echo "::set-output name=result::0"
        id: diff1
      - run: echo "::set-output name=result::1"
        id: diff2
      - run: echo hello
        if: steps.diff1.outputs.result
      - run: echo hello
        if: steps.diff1.outputs.result == 0
      - run: echo hello
        if: steps.diff1.outputs.result == '0'
      - run: echo hello
        if: steps.diff2.outputs.result
      - run: echo hello
        if: steps.diff2.outputs.result == 1
      - run: echo hello
        if: steps.diff2.outputs.result == '1'
      - run: ex --help
      - run: echo test > test.txt
      - run: sed -i.bak -e 's/test/TEST/' test.txt
      - run: cat test.txt
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            console.log("Hello");
      - uses: actions/github-script@v6
        with:
          script: |
            const globber = await glob.create('**');
            const files = await globber.glob();

            console.log(files);
      - uses: actions/github-script@v6
        with:
          script: |
            const globber = await glob.create('.github/**');
            const files = await globber.glob();

            console.log(files);
  command:
    name: command
    strategy:
      matrix:
        os:
          - windows-2022
          - macos-14
          - ubuntu-22.04
    runs-on: ubuntu-latest
    steps:
      - run: type rsync
        continue-on-error: true
      - run: type cpio
        continue-on-error: true
      - run: type pax
        continue-on-error: true
      - run: type install
        continue-on-error: true
