name: sandbox

on:
  - push
  - pull_request

jobs:
  sandbox:
    name: sandbox
    strategy:
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - run: pwd
      - run: ls -la
        shell: bash
      - run: ls -la /
        shell: bash
      - id: set_data1
        run: echo "::set-output name=expr::$(expr 1 + 1)"
      - id: set_data2
        run: echo "::set-output name=path::${PATH}"
      - id: set_data3
        run: echo "::set-output name=cdir::$(pwd)"
      - run: |
          echo $EXPR
          echo $PATH
          echo $CDIR
        env:
          EXPR: ${{ steps.set_data1.outputs.expr }}
          PATH: ${{ steps.set_data2.outputs.path }}
          CDIR: ${{ steps.set_data3.outputs.cdir }}
      - run: echo $PATH | tr ':' '\n'
      - run: echo "::add-path::/path/to/dir1"
      - run: echo "::add-path::/path/to/dir2"
      - run: echo '::add-path::/path/to/dir3'
      - run: echo $PATH | tr ':' '\n'
      - run: |
          echo "::add-path::/path/to/dir4"
          echo "::add-path::/path/to/dir5"
          echo '::add-path::/path/to/dir6'
      - run: echo $PATH | tr ':' '\n'
      - id: boolean_check1
        run: echo '::set-output name=flag::true'
      - run: echo true
        if: steps.boolean_check1.outputs.flag
      - run: echo true
        if: steps.boolean_check1.outputs.flag == true
      - run: echo true
        if: steps.boolean_check1.outputs.flag == 'true'
      - id: boolean_check2
        run: echo '::set-output name=flag::1'
      - run: echo true
        if: steps.boolean_check2.outputs.flag
      - run: echo true
        if: steps.boolean_check2.outputs.flag == true
      - run: echo true
        if: steps.boolean_check2.outputs.flag == 'true'
