name: sandbox

on:
  - push
  - pull_request

jobs:
  sandbox:
    name: sandbox
    strategy:
      matrix:
        os:
          - windows-latest
          - macOS-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - run: env
      - run: pwd -P
      - run: ls -la
      - run: ls -la /
