name: show github

on:
  - push

jobs:
  show-github:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJSON(github) }}'
      - run: echo '${{ runner.name }}'
      - run: echo '${{ toJSON(runner) }}'
