name: use-job-output

on:
  - push

jobs:
  output:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { id: 1 }
          - { id: 2 }
          - { id: 3 }
    steps:
      - run: echo 'hello-${{ matrix.id }}' >> file.txt
      - uses: actions/upload-artifact@v3
        with:
          name: file-${{ matrix.id }}
          path: file.txt
  print:
    runs-on: ubuntu-latest
    needs: output
    steps:
      - uses: actions/download-artifact@v3
      - run: ls -l
      - run: ls -l file-*
