name: use-job-output

on:
  - push

jobs:
  output:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { id: 1 }
          - { id: 2 }
          - { id: 3 }
    outputs:
      stdout: ${{ steps.out.outputs.test }}
    steps:
      - run: echo "::set-output name=test::${{ steps.out.outputs.test }},hello-${{ matrix.id }}"
        id: out
  print:
    runs-on: ubuntu-latest
    needs: output
    steps:
      - run: echo "${{ needs.output.outputs.stdout }}"
